### ISSUE TITLE
Автогрупировка

### ISSUE THREAD

**Issue by gwynnbleiidd** [proteye/keywords-grouper#1]
Приветствую, проверил на досуге скрипт.
Понравился, как раз для обычной групировки самое то)

Вопрос, возможно ли сделать автогрупировку как у ребят из http://kg.ppc-panel.ru/
Делается при зажатии A+Tab в английской раскладке. Я видел упоминание в JS файлах, через firebug можно изучить, но у самого знаний мало что бы прикрутить такое :)

**Comment by proteye** [comment]
Приветствую! Извините, что с запозданием. Почему-то не увидел ваш issue.
Прикрутить, то можно. Весь вопрос в следующем - алгоритм автогруппировки, время и желание прикрутить эту автогруппировку. К сожалению в ближайшем будущем я не смогу этим заняться из-за отсутствия свободного времени.
